// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJ9IkgXtwU-5K0sxPnYiEov7QRMUjS7ZA',
    appId: '1:973063477698:web:1de01a0f0035b266b05e5b',
    messagingSenderId: '973063477698',
    projectId: 'fashtask',
    authDomain: 'fashtask.firebaseapp.com',
    storageBucket: 'fashtask.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3tUnoqXt9yVcb8Ufq2x1WrNQ4QTeLN_Q',
    appId: '1:973063477698:android:232d041022c52bb7b05e5b',
    messagingSenderId: '973063477698',
    projectId: 'fashtask',
    storageBucket: 'fashtask.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcWxUR9Yf6CTTfpKXBMSQh1mvq-k0uULA',
    appId: '1:973063477698:ios:441bbec647de7d6eb05e5b',
    messagingSenderId: '973063477698',
    projectId: 'fashtask',
    storageBucket: 'fashtask.appspot.com',
    iosBundleId: 'com.example.fashtask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcWxUR9Yf6CTTfpKXBMSQh1mvq-k0uULA',
    appId: '1:973063477698:ios:441bbec647de7d6eb05e5b',
    messagingSenderId: '973063477698',
    projectId: 'fashtask',
    storageBucket: 'fashtask.appspot.com',
    iosBundleId: 'com.example.fashtask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJ9IkgXtwU-5K0sxPnYiEov7QRMUjS7ZA',
    appId: '1:973063477698:web:b82ae0353e3b3f70b05e5b',
    messagingSenderId: '973063477698',
    projectId: 'fashtask',
    authDomain: 'fashtask.firebaseapp.com',
    storageBucket: 'fashtask.appspot.com',
  );
}
